import java.util.ListResourceBundle;

/**
 * Represents a bank customer with personal and contact details.
 * <p>
 * Each customer has a unique internal ID (e.g., {@code C001}) generated by the system
 * and a unique national identification number (CNP). Instances are used to open accounts
 * and manage banking relationships.
 * 
 *
 * <p>
 * Some properties may be used by authentication/user management (e.g., in {@link User}),
 * while others define the customer's identity and address.
 * 
 *
 * author Ilinca Rusescu
 * @version 1.2
 */

public class Customer {
    /** Internal customer ID used by the bank system (e.g., "C001"). */
    private final String customerId;

    /** Customer's first name (e.g., "Ana"). */
    private String firstName;

    /** Customer's last name (e.g., "Pop"). */
    private String lastName;

    /** Customer's age in years. */
    private int age;

    /** Customer's gender ("Male", "Female", or "Other"). */
    private String gender;

    /** Customer's email address. */
    private String email;

    /** Customer's phone number. */
    private String phoneNumber;

    /** Customer's national personal identification number (CNP). */
    private final String cnp;

    /** Primary address line (street, number, etc.). */
    private final String addressLine1;

    /** Secondary address line (optional, may be empty). */
    private final String addressLine2;

    /** City of residence. */
    private final String city;

    /** Postal code for the address (e.g., "010101"). */
    private final String postalCode;

    /** Country of residence (2-letter ISO code, e.g., "RO"). */
    private final String country;



    // -----------------------------------------------------
    // CONSTRUCTOR
    // -----------------------------------------------------

    /**
     * Contruscts a new {@code Customer} with personal, contact, and address details.
     *
     * @param firstName     customer's first name
     * @param lastName      customer's last name
     * @param age           customer's age (must be >= 18)
     * @param gender        customer's gender
     * @param email         customer's email address
     * @param phoneNumber   customer's phone number (10 digits)
     * @param cnp           national identification number (13 digits, unique)
     * @param addressLine1  main address line (required)
     * @param addressLine2  optional address line (can be empty)
     * @param city          customer's city
     * @param postalCode    postal code (numeric, 4–6 digits)
     * @param country       2-letter ISO country code (e.g., "RO")
     * @throws IllegalArgumentException if any validation fails
     */

    public Customer(String firstName, String lastName, int age, String gender,
                    String email, String phoneNumber, String cnp,
                    String addressLine1, String addressLine2, String city,
                    String postalCode, String country) {

        // --- Validations ---
        if (isBlank(firstName)) throw new IllegalArgumentException("First name cannot be blank.");
        if (isBlank(lastName)) throw new IllegalArgumentException("Last name cannot be blank.");
        if (age<18) throw new IllegalArgumentException("Customer must be at least 18 years old.");
        if (isBlank(gender)) throw new IllegalArgumentException("Gender cannot be blank.");
        if (isBlank(email)) throw new IllegalArgumentException("Invalid email.");
        if (isBlank(phoneNumber) || phoneNumber.length() != 10)
            throw new IllegalArgumentException("Ivalid phone number.");
        if (isBlank(cnp) || cnp.length() != 13)
            throw new InvalidCnpException("Invalid CNP (must have 13 digits).");
        if (isBlank(addressLine1)) throw new IllegalArgumentException("Address line 1 cannot be blank.");
        if (isBlank(city)) throw new IllegalArgumentException("City cannot be blank.");
        if (isBlank(postalCode) || postalCode.length() < 4 || postalCode.length() > 6)
            throw new IllegalArgumentException("Invalid postal code (must be 4–6 digits).");
        if (isBlank(country) || country.length() != 2)
            throw new IllegalArgumentException("Country must be a 2-letter ISO code (e.g., 'RO').");

        // --- Assignments ---
        this.customerId = IdGenerator.nextCustomerId();
        this.firstName = firstName.trim();
        this.lastName = lastName.trim();
        this.age = age;
        this.gender = gender.trim();
        this.email = email.trim();
        this.phoneNumber = phoneNumber.trim();
        this.cnp = cnp.trim();
        this.addressLine1 = addressLine1.trim();
        this.addressLine2 = (addressLine2 == null) ? "" : addressLine2.trim();
        this.city = city.trim();
        this.postalCode = postalCode.trim();
        this.country = country.trim().toUpperCase();
    }

    // -----------------------------------------------------
    // Getters
    // -----------------------------------------------------

    /** @return internal customer ID (e.g., "C001") */
    public String getCustomerId() { return customerId; }

    /** @return customer's first name */
    public String getFirstName() { return firstName; }

    /** @return customer's last name */
    public String getLastName() { return lastName; }

    /** @return customer's full name (first + last) */
    public String getFullName() { return this.firstName + " " + this.lastName; }

    /** @return customer's age */
    public int getAge() { return age; }

    /** @return customer's gender */
    public String getGender() { return gender; }

    /** @return customer's email address */
    public String getEmail() { return email; }

    /** @return customer's phone number */
    public String getPhoneNumber() { return phoneNumber; }

    /** @return customer's national identification number (CNP) */
    public String getCnp() { return cnp; }

    /** @return first address line (street, number, etc.) */
    public String getAddressLine1() { return addressLine1; }

    /** @return second address line (optional, may be empty) */
    public String getAddressLine2() { return addressLine2; }

    /** @return city of residence */
    public String getCity() { return city; }

    /** @return postal code */
    public String getPostalCode() { return postalCode; }

    /** @return country of residence (2-letter ISO code) */
    public String getCountry() { return country; }

    // --- Setters (for editable fields only) ---

    /**
     * Updates the customer's contact details.
     *
     * @param email new email address (must contain '@')
     * @param phone new phone number (10 digits)
     * @throws IllegalArgumentException if inputs are invalid
     */

    public void updateContact(String email, String phone){
        if (isBlank(email) || !email.contains("@"))
            throw new IllegalArgumentException("Invalid email address.");
        if (isBlank(phone) || phone.length() != 10)
            throw new IllegalArgumentException("Invalid phone number");

        this.email=email;
        this.phoneNumber = phone;
    }

    // =============================
    //           UTILITIES
    // =============================

    /**
     * @return readable string representation of the customer
     */

    @Override
    public String toString() {
        return "Customer{" +
                "customerId='" + customerId + '\'' +
                ", name='" + getFullName() + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", cnp='" + cnp + '\'' +
                ", address='" + addressLine1 +
                (addressLine2.isEmpty() ? "" : ", " + addressLine2) +
                ", " + city + " " + postalCode + ", " + country + '\'' +
                '}';
    }

    /** @return {@code true} if the string is null, empty, or whitespace-only */
    private static boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }
}
